/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicesystem.home;

import invoiceProject.dbConinvoice;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Al-RaZi
 */
public class AppUserManager extends javax.swing.JFrame {

    PreparedStatement pst;
    dbConinvoice dbConn = new dbConinvoice();
    String[] columns={"EMPID", "Name", "UserName", "Password", "Role", "Email", "Contact" };
    
     public void clear(){
        dbEmpid.setText("");
        dbName.setText("");
        dbUsername.setText("");
        dbPassword.setText("");
        dbRole.setSelectedItem("");
        dbEmail.setText("");
        dbContact.setText("");
        
    }
    
    public void showData() throws SQLException{
    
        String sql="select * from appusers";
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        userTable.setModel(model);
        ResultSet rs;
        
        try {
            pst = dbConn.getCon().prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String empid = rs.getString("empid");
                String name = rs.getString("name");
                String username = rs.getString("username");
                String password = rs.getString("password");
                String role = rs.getString("role");
                String email = rs.getString("email");
                String contact = rs.getString("contact");
                
                model.addRow(new Object[]{empid, name, username, password, role, email, contact });
                
        
        }
            
            pst.close();
            dbConn.getCon().close();
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    public AppUserManager() {
        initComponents();
        
        

        
        try {
            showData();
        } catch (SQLException ex) {
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dbEmpid = new javax.swing.JTextField();
        dbName = new javax.swing.JTextField();
        dbEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dbContact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        dbPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dbUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dbRole.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        dbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Role", "Manager", "Customer Support" }));
        getContentPane().add(dbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 200, -1));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 940, 270));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("EMID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, 26));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 140, 24));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 140, 25));

        dbEmpid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbEmpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 201, -1));

        dbName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 201, -1));

        dbEmail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 201, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 201, 20));

        dbContact.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 201, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Contact");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 201, 26));

        btnUpdate.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("To Update The Data!");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        btnDelete.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("To Delete The Data!");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        btnReset.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnReset.setText("Reset!");
        btnReset.setToolTipText("To Reset The Value!");
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        dbPassword.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 201, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1020, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/userlist-management.png"))); // NOI18N
        jLabel8.setText("App User Manager");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 380, 70));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, -1));

        dbUsername.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        getContentPane().add(dbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 170, -1));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/home- 32 X 32.png"))); // NOI18N
        jButton1.setText("Back to Homepage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 190, 40));

        jButton2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/out-2 - 32 X 32.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/User-Manager.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        
        int rowNumber = userTable.getSelectedRow();
        
        String empid = userTable.getModel().getValueAt(rowNumber,0).toString();
        String name = userTable.getModel().getValueAt(rowNumber, 1).toString();
        String username = userTable.getModel().getValueAt(rowNumber, 2).toString();
        String password = userTable.getModel().getValueAt(rowNumber, 3).toString();
        String role = userTable.getModel().getValueAt(rowNumber, 4).toString();
        String email = userTable.getModel().getValueAt(rowNumber, 5).toString();
        String contact = userTable.getModel().getValueAt(rowNumber, 6).toString();
        
        dbEmpid.setText(empid);
        dbName.setText(name);
        dbUsername.setText(username);
        dbPassword.setText(password);
        dbRole.setSelectedItem(role);
        dbEmail.setText(email);
        dbContact.setText(contact);
        
        
    }//GEN-LAST:event_userTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String sql = "update appusers set name=?, username=?,  password=?, role=?, email=?, contact=? where empid=?";
        
        try {
            pst = dbConn.getCon().prepareStatement(sql);
            
            pst.setString(1, dbName.getText().trim());
            pst.setString(2, dbUsername.getText().trim());
            pst.setString(3, dbPassword.getText().trim());
            pst.setString(4, dbRole.getItemAt(0));
            pst.setString(5, dbEmail.getText().trim());
            pst.setString(6, dbContact.getText().trim());
            pst.setString(7, dbEmpid.getText());

             pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "User Data Updated!");
            showData();
            clear();
            pst.close();
            dbConn.getCon().close();
            
            
            
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "User Data Updated! Failed!");
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        String sql = "delete from appusers where empid=?";
        try {
            pst = dbConn.getCon().prepareStatement(sql);
            pst.setString(1, dbEmpid.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "User Data Deleted!");
            showData();
            clear();
            pst.close();
            dbConn.getCon().close();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Failed! Data Not Deleted!");
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppUserManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUserManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField dbContact;
    private javax.swing.JTextField dbEmail;
    private javax.swing.JTextField dbEmpid;
    private javax.swing.JTextField dbName;
    private javax.swing.JPasswordField dbPassword;
    private javax.swing.JComboBox<String> dbRole;
    private javax.swing.JTextField dbUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
