/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicesystem.home;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Al-RaZi
 */
public class Homepage extends javax.swing.JFrame {
    public int inHome =0;
    
    
   
   


    /**
     * Creates new form Homepage
     */


 
    
    public Homepage() {
        initComponents();
        
        //Title of the window Assign
        this.setTitle("MiXed Invoice - HomePage");
        
        
        btnhomeInvoice.setVisible(false);
        btnTransactions.setVisible(false);
        btnhomeNewclient.setVisible(false);
        btnhomeUpdateclient.setVisible(false);
        btnhomeAllclient.setVisible(false);
        btnhomeRemoveclient.setVisible(false);
        btnhomeAddproducts.setVisible(false);
        btnhomeUpdateproducts.setVisible(false);
        btnhomeProductlist.setVisible(false);
        btnhomeRemoveproducts.setVisible(false);
        btnhomeSignupUser.setVisible(false);
        btnhomeUpdateUser.setVisible(false);
        btnhomeInfo.setVisible(false);
        btnhomeSignout.setVisible(false);
        btnhomeShutdown.setVisible(false);
        
        labelhomeInvoice.setVisible(false);
        labelTransactions.setVisible(false);
        labelhomeNewAppUser.setVisible(false);
        labelhomeUpdateuser.setVisible(false);
        labelhomeAllclient.setVisible(false);
        labelhomeRemoveClient.setVisible(false);
        labelhomeAddproduct.setVisible(false);
        labelhomeUpdateProduct.setVisible(false);
        labelhomeProductlist.setVisible(false);
        labelhomeRemoveproduct.setVisible(false);
        labelhomeSignupuser.setVisible(false);
        labelhomeUpdateNewuser.setVisible(false);
        labelhomeInfo.setVisible(false);
        txtLog.setVisible(false);
        txtUserlog.setVisible(false);
        labelPlate.setVisible(false);
        labelhomeSignout.setVisible(false);
        labelhomeShutdown.setVisible(false);

        
        
        
        

    }
    
 public Homepage(String userName) {
      
            initComponents();
         txtUserlog.setText(userName);
         
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnhomeInvoice = new javax.swing.JButton();
        labelhomeInvoice = new javax.swing.JLabel();
        btnhomeNewclient = new javax.swing.JButton();
        labelhomeNewAppUser = new javax.swing.JLabel();
        btnhomeUpdateclient = new javax.swing.JButton();
        labelhomeUpdateuser = new javax.swing.JLabel();
        btnhomeAllclient = new javax.swing.JButton();
        labelhomeAllclient = new javax.swing.JLabel();
        btnhomeRemoveclient = new javax.swing.JButton();
        labelhomeRemoveClient = new javax.swing.JLabel();
        btnhomeAddproducts = new javax.swing.JButton();
        labelhomeAddproduct = new javax.swing.JLabel();
        btnhomeUpdateproducts = new javax.swing.JButton();
        labelhomeUpdateProduct = new javax.swing.JLabel();
        btnhomeRemoveproducts = new javax.swing.JButton();
        labelhomeRemoveproduct = new javax.swing.JLabel();
        btnhomeProductlist = new javax.swing.JButton();
        labelhomeProductlist = new javax.swing.JLabel();
        labelhomeSignupuser = new javax.swing.JLabel();
        btnhomeSignupUser = new javax.swing.JButton();
        btnhomeInfo = new javax.swing.JButton();
        txtUserlog = new javax.swing.JLabel();
        txtLog = new javax.swing.JLabel();
        labelPlate = new javax.swing.JLabel();
        labelhomeInfo = new javax.swing.JLabel();
        btnhomeUpdateUser = new javax.swing.JButton();
        labelhomeUpdateNewuser = new javax.swing.JLabel();
        btnTransactions = new javax.swing.JButton();
        labelTransactions = new javax.swing.JLabel();
        labelhomeShutdown = new javax.swing.JLabel();
        btnhomeShutdown = new javax.swing.JButton();
        labelhomeSignout = new javax.swing.JLabel();
        btnhomeSignout = new javax.swing.JButton();
        btnhomeCollapse = new javax.swing.JButton();
        labelMixed = new javax.swing.JLabel();
        labelClick = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhomeInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/billing.png"))); // NOI18N
        btnhomeInvoice.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeInvoiceComponentShown(evt);
            }
        });
        btnhomeInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 110));

        labelhomeInvoice.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeInvoice.setText("Invoice");
        getContentPane().add(labelhomeInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 74, -1));

        btnhomeNewclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/new-user.png"))); // NOI18N
        btnhomeNewclient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeNewclientComponentShown(evt);
            }
        });
        btnhomeNewclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeNewclientActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeNewclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, 110));

        labelhomeNewAppUser.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeNewAppUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeNewAppUser.setText("New Client");
        getContentPane().add(labelhomeNewAppUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 87, 17));

        btnhomeUpdateclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/update-user.png"))); // NOI18N
        btnhomeUpdateclient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeUpdateclientComponentShown(evt);
            }
        });
        btnhomeUpdateclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeUpdateclientActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeUpdateclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 110, 110));

        labelhomeUpdateuser.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeUpdateuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeUpdateuser.setText("Update Client");
        getContentPane().add(labelhomeUpdateuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        btnhomeAllclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user-details.png"))); // NOI18N
        btnhomeAllclient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeAllclientComponentShown(evt);
            }
        });
        btnhomeAllclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeAllclientActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeAllclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 110, 110));

        labelhomeAllclient.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeAllclient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeAllclient.setText("All Client");
        getContentPane().add(labelhomeAllclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, -1, -1));

        btnhomeRemoveclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/remove-user.png"))); // NOI18N
        btnhomeRemoveclient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeRemoveclientComponentShown(evt);
            }
        });
        btnhomeRemoveclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeRemoveclientActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeRemoveclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 110, 110));

        labelhomeRemoveClient.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeRemoveClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeRemoveClient.setText("Remove Client");
        getContentPane().add(labelhomeRemoveClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, -1, -1));

        btnhomeAddproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add-product.png"))); // NOI18N
        btnhomeAddproducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeAddproductsComponentShown(evt);
            }
        });
        btnhomeAddproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeAddproductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeAddproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 110, 100));

        labelhomeAddproduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeAddproduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeAddproduct.setText("Add Products");
        getContentPane().add(labelhomeAddproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        btnhomeUpdateproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/update-product.png"))); // NOI18N
        btnhomeUpdateproducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeUpdateproductsComponentShown(evt);
            }
        });
        btnhomeUpdateproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeUpdateproductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeUpdateproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 110, 100));

        labelhomeUpdateProduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeUpdateProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeUpdateProduct.setText("Update Products");
        getContentPane().add(labelhomeUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        btnhomeRemoveproducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/remove-product.png"))); // NOI18N
        btnhomeRemoveproducts.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeRemoveproductsComponentShown(evt);
            }
        });
        btnhomeRemoveproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeRemoveproductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeRemoveproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 110, 100));

        labelhomeRemoveproduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeRemoveproduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeRemoveproduct.setText("Remove Products");
        getContentPane().add(labelhomeRemoveproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        btnhomeProductlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/product-details.png"))); // NOI18N
        btnhomeProductlist.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeProductlistComponentShown(evt);
            }
        });
        btnhomeProductlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeProductlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeProductlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 110, 100));

        labelhomeProductlist.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeProductlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeProductlist.setText("Product List");
        getContentPane().add(labelhomeProductlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        labelhomeSignupuser.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeSignupuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeSignupuser.setText("SignUp User");
        getContentPane().add(labelhomeSignupuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 87, 17));

        btnhomeSignupUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/signup-useroff.png"))); // NOI18N
        btnhomeSignupUser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeSignupUserComponentShown(evt);
            }
        });
        btnhomeSignupUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeSignupUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeSignupUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 110, 110));

        btnhomeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/info-64x64.png"))); // NOI18N
        btnhomeInfo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeInfoComponentShown(evt);
            }
        });
        btnhomeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 450, 110, 110));

        txtUserlog.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtUserlog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtUserlogComponentShown(evt);
            }
        });
        getContentPane().add(txtUserlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 140, 30));

        txtLog.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtLog.setText("Logged in");
        txtLog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtLogComponentShown(evt);
            }
        });
        getContentPane().add(txtLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 70, 30));

        labelPlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/name-plate.png"))); // NOI18N
        getContentPane().add(labelPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 260, -1));

        labelhomeInfo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeInfo.setText("Info");
        getContentPane().add(labelhomeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 570, 87, 17));

        btnhomeUpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user-signup.png"))); // NOI18N
        btnhomeUpdateUser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeUpdateUserComponentShown(evt);
            }
        });
        btnhomeUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeUpdateUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeUpdateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 110, 110));

        labelhomeUpdateNewuser.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeUpdateNewuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeUpdateNewuser.setText("Update User");
        getContentPane().add(labelhomeUpdateNewuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 87, 17));

        btnTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/report-64x64.png"))); // NOI18N
        btnTransactions.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnTransactionsComponentShown(evt);
            }
        });
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, 110));

        labelTransactions.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelTransactions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransactions.setText("TransactionX");
        getContentPane().add(labelTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        labelhomeShutdown.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeShutdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeShutdown.setText("Shut Down");
        getContentPane().add(labelhomeShutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, -1, -1));

        btnhomeShutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/shut-down.png"))); // NOI18N
        btnhomeShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeShutdownActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeShutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 600, 110, 110));

        labelhomeSignout.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelhomeSignout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhomeSignout.setText("Sign-Out");
        getContentPane().add(labelhomeSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 720, -1, -1));

        btnhomeSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/sign-out.png"))); // NOI18N
        btnhomeSignout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnhomeSignoutComponentShown(evt);
            }
        });
        btnhomeSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeSignoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnhomeSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 110, 110));

        btnhomeCollapse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/userpan.png"))); // NOI18N
        btnhomeCollapse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeCollapseMouseClicked(evt);
            }
        });
        getContentPane().add(btnhomeCollapse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 100));

        labelMixed.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        labelMixed.setText("Welcome to MiXed Invoice System");
        getContentPane().add(labelMixed, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 440, 80));

        labelClick.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelClick.setText("Click n Expand");
        getContentPane().add(labelClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cover-bg-3.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeSignoutActionPerformed
        // TODO add your handling code here:
        
        int lout = JOptionPane.showConfirmDialog(null, "Do You Really Want to Logout", "Select ",JOptionPane.YES_NO_OPTION);
        
        if (lout ==0){
            setVisible(false);
            new Login().setVisible(true);
            
        
        }
    }//GEN-LAST:event_btnhomeSignoutActionPerformed

    private void btnhomeCollapseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeCollapseMouseClicked
        // TODO add your handling code here:
        if(inHome==0){
            try {
                Thread.sleep(75);
                btnhomeInvoice.setVisible(true);
                labelhomeInvoice.setVisible(true);
            } catch (Exception e) {
            }
        }
        else{
         btnhomeInvoice.setVisible(false);
          btnTransactions.setVisible(false);
        btnhomeNewclient.setVisible(false);
        btnhomeUpdateclient.setVisible(false);
        btnhomeAllclient.setVisible(false);
        btnhomeRemoveclient.setVisible(false);
        btnhomeAddproducts.setVisible(false);
        btnhomeUpdateproducts.setVisible(false);
        btnhomeProductlist.setVisible(false);
        btnhomeRemoveproducts.setVisible(false);
        btnhomeSignupUser.setVisible(false);
        btnhomeUpdateUser.setVisible(false);
        btnhomeInfo.setVisible(false);
        btnhomeSignout.setVisible(false);
        btnhomeShutdown.setVisible(false);
        
        labelhomeInvoice.setVisible(false);
         labelTransactions.setVisible(false);
        labelhomeNewAppUser.setVisible(false);
        labelhomeUpdateuser.setVisible(false);
        labelhomeAllclient.setVisible(false);
        labelhomeRemoveClient.setVisible(false);
        labelhomeAddproduct.setVisible(false);
        labelhomeUpdateProduct.setVisible(false);
        labelhomeProductlist.setVisible(false);
        labelhomeRemoveproduct.setVisible(false);
        labelhomeSignupuser.setVisible(false);
        labelhomeUpdateNewuser.setVisible(false);
        labelhomeInfo.setVisible(false);
        labelhomeSignout.setVisible(false);
        labelhomeShutdown.setVisible(false);
        
        inHome=0;
        
        }
        
    }//GEN-LAST:event_btnhomeCollapseMouseClicked

    private void btnhomeInvoiceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeInvoiceComponentShown
        // TODO add your handling code here:
        

            try {
                Thread.sleep(75);
                btnhomeNewclient.setVisible(true);
                labelhomeNewAppUser.setVisible(true);
            } catch (Exception e) {
            }
            
        
    }//GEN-LAST:event_btnhomeInvoiceComponentShown

    private void btnhomeNewclientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeNewclientComponentShown
        // TODO add your handling code here:
        
        try {
                Thread.sleep(75);
                btnhomeUpdateclient.setVisible(true);
                labelhomeUpdateuser.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeNewclientComponentShown

    private void btnhomeUpdateclientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeUpdateclientComponentShown
        // TODO add your handling code here:
              try {
                Thread.sleep(75);
                btnhomeAllclient.setVisible(true);
                labelhomeAllclient.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeUpdateclientComponentShown

    private void btnhomeAllclientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeAllclientComponentShown
        // TODO add your handling code here:
                try {
                Thread.sleep(75);
                btnhomeRemoveclient.setVisible(true);
                labelhomeRemoveClient.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeAllclientComponentShown

    private void btnhomeRemoveclientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeRemoveclientComponentShown
        // TODO add your handling code here:
                        try {
                Thread.sleep(75);
                btnhomeAddproducts.setVisible(true);
                labelhomeAddproduct.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeRemoveclientComponentShown

    private void btnhomeAddproductsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeAddproductsComponentShown
        // TODO add your handling code here:
                        try {
                Thread.sleep(75);
                btnhomeUpdateproducts.setVisible(true);
                labelhomeUpdateProduct.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeAddproductsComponentShown

    private void btnhomeRemoveproductsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeRemoveproductsComponentShown
        // TODO add your handling code here:
                                try {
                Thread.sleep(75);
                btnTransactions.setVisible(true);
                labelTransactions.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeRemoveproductsComponentShown

    private void btnhomeProductlistComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeProductlistComponentShown
        // TODO add your handling code here:
                try {
                Thread.sleep(75);
                btnhomeRemoveproducts.setVisible(true);
                labelhomeRemoveproduct.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeProductlistComponentShown

    private void btnhomeSignoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeSignoutComponentShown
        // TODO add your handling code here:
            try {
                Thread.sleep(75);
                btnhomeShutdown.setVisible(true);
                labelhomeShutdown.setVisible(true);
                inHome =1;
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeSignoutComponentShown

    private void btnhomeUpdateproductsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeUpdateproductsComponentShown
        // TODO add your handling code here:
                try {
                Thread.sleep(75);
                btnhomeProductlist.setVisible(true);
                labelhomeProductlist.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnhomeUpdateproductsComponentShown

    private void btnhomeNewclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeNewclientActionPerformed
        // TODO add your handling code here:

        new NewClient().setVisible(true);
        
    }//GEN-LAST:event_btnhomeNewclientActionPerformed

    private void btnhomeUpdateclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeUpdateclientActionPerformed
        // TODO add your handling code here:
        new UpdateClient().setVisible(true);
    }//GEN-LAST:event_btnhomeUpdateclientActionPerformed

    private void btnhomeAllclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeAllclientActionPerformed
        // TODO add your handling code here:
        new ClientList().setVisible(true);
    }//GEN-LAST:event_btnhomeAllclientActionPerformed

    private void btnhomeRemoveclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeRemoveclientActionPerformed
        // TODO add your handling code here:
        new RemoveClient().setVisible(true);
    }//GEN-LAST:event_btnhomeRemoveclientActionPerformed

    private void btnhomeAddproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeAddproductsActionPerformed
        // TODO add your handling code here:
        new AddProducts().setVisible(true);
        
    }//GEN-LAST:event_btnhomeAddproductsActionPerformed

    private void btnhomeUpdateproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeUpdateproductsActionPerformed
        // TODO add your handling code here:
        new UpdateProducts().setVisible(true);
    }//GEN-LAST:event_btnhomeUpdateproductsActionPerformed

    private void btnhomeProductlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeProductlistActionPerformed
        // TODO add your handling code here:
        new ListProduct().setVisible(true);
        
    }//GEN-LAST:event_btnhomeProductlistActionPerformed

    private void btnhomeRemoveproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeRemoveproductsActionPerformed
        // TODO add your handling code here:
        
         new RemoveProducts().setVisible(true);
    }//GEN-LAST:event_btnhomeRemoveproductsActionPerformed

    private void btnhomeInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeInvoiceActionPerformed
        // TODO add your handling code here:
         new InvoiceSys().setVisible(true);
    }//GEN-LAST:event_btnhomeInvoiceActionPerformed

    private void txtLogComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtLogComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(75);
                btnhomeUpdateclient.setVisible(true);
                labelhomeUpdateuser.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_txtLogComponentShown

    private void txtUserlogComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtUserlogComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(75);
                btnhomeUpdateclient.setVisible(true);
                labelhomeUpdateuser.setVisible(true);
            } catch (Exception e) {
            }
    }//GEN-LAST:event_txtUserlogComponentShown

    private void btnTransactionsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnTransactionsComponentShown
// TODO add your handling code here:
 try {
                Thread.sleep(75);
                btnhomeSignupUser.setVisible(true);
                labelhomeSignupuser.setVisible(true);
            } catch (Exception e) {
            }

      
       
    }//GEN-LAST:event_btnTransactionsComponentShown

    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
        // TODO add your handling code here:
        
        new TrxHistory().setVisible(true);
    }//GEN-LAST:event_btnTransactionsActionPerformed

    private void btnhomeSignupUserComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeSignupUserComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(75);
                btnhomeUpdateUser.setVisible(true);
                labelhomeUpdateNewuser.setVisible(true);
            } catch (Exception e) {
            }
        
        
    }//GEN-LAST:event_btnhomeSignupUserComponentShown

    private void btnhomeSignupUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeSignupUserActionPerformed
        // TODO add your handling code here:
         new CreateUsers().setVisible(true);
    }//GEN-LAST:event_btnhomeSignupUserActionPerformed

    private void btnhomeUpdateUserComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeUpdateUserComponentShown
        // TODO add your handling code here:
         try {
                Thread.sleep(75);
                btnhomeInfo.setVisible(true);
                labelhomeInfo.setVisible(true);
            } catch (Exception e) {
            }
        
    }//GEN-LAST:event_btnhomeUpdateUserComponentShown

    private void btnhomeUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeUpdateUserActionPerformed
        // TODO add your handling code here:
        new AppUserManager().setVisible(true);
    }//GEN-LAST:event_btnhomeUpdateUserActionPerformed

    private void btnhomeShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeShutdownActionPerformed
        // TODO add your handling code here:
        int discard = JOptionPane.showConfirmDialog(null, "Do You Want to Exit Session!","Select",JOptionPane.YES_NO_OPTION);
        
        if (discard==0){
        System.exit(0);
        
        }
    }//GEN-LAST:event_btnhomeShutdownActionPerformed

    private void btnhomeInfoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnhomeInfoComponentShown
        // TODO add your handling code here:
        try {
                Thread.sleep(75);
                btnhomeSignout.setVisible(true);
                labelhomeSignout.setVisible(true);
                txtLog.setVisible(true);
                txtUserlog.setVisible(true);
                labelPlate.setVisible(true);
            } catch (Exception e) {
            }  
         
    }//GEN-LAST:event_btnhomeInfoComponentShown

    private void btnhomeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeInfoActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_btnhomeInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnhomeAddproducts;
    private javax.swing.JButton btnhomeAllclient;
    private javax.swing.JButton btnhomeCollapse;
    private javax.swing.JButton btnhomeInfo;
    private javax.swing.JButton btnhomeInvoice;
    private javax.swing.JButton btnhomeNewclient;
    private javax.swing.JButton btnhomeProductlist;
    private javax.swing.JButton btnhomeRemoveclient;
    private javax.swing.JButton btnhomeRemoveproducts;
    private javax.swing.JButton btnhomeShutdown;
    private javax.swing.JButton btnhomeSignout;
    private javax.swing.JButton btnhomeSignupUser;
    private javax.swing.JButton btnhomeUpdateUser;
    private javax.swing.JButton btnhomeUpdateclient;
    private javax.swing.JButton btnhomeUpdateproducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel labelClick;
    private javax.swing.JLabel labelMixed;
    private javax.swing.JLabel labelPlate;
    private javax.swing.JLabel labelTransactions;
    private javax.swing.JLabel labelhomeAddproduct;
    private javax.swing.JLabel labelhomeAllclient;
    private javax.swing.JLabel labelhomeInfo;
    private javax.swing.JLabel labelhomeInvoice;
    private javax.swing.JLabel labelhomeNewAppUser;
    private javax.swing.JLabel labelhomeProductlist;
    private javax.swing.JLabel labelhomeRemoveClient;
    private javax.swing.JLabel labelhomeRemoveproduct;
    private javax.swing.JLabel labelhomeShutdown;
    private javax.swing.JLabel labelhomeSignout;
    private javax.swing.JLabel labelhomeSignupuser;
    private javax.swing.JLabel labelhomeUpdateNewuser;
    private javax.swing.JLabel labelhomeUpdateProduct;
    private javax.swing.JLabel labelhomeUpdateuser;
    private javax.swing.JLabel txtLog;
    private javax.swing.JLabel txtUserlog;
    // End of variables declaration//GEN-END:variables
}
