/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicesystem.home;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import invoiceProject.dbConinvoice;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.*;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Al-RaZi
 */
public class InvoiceSys extends javax.swing.JFrame {

    
        dbConinvoice dbConn = new dbConinvoice();
        PreparedStatement pst;
        
        
        public float subtotal =0;
      

    /**
     * Creates new form InvoiceSys
     */
    
            public void invoiceid(){
        Random invoGen = new Random();
        
        int n = invoGen.nextInt(10000)+1;
        String val= String.valueOf(n);
        
        Random random2 = new Random();
        String alpha ="ABCINVABCINV";
                for (int i = 0; i < 10; i++) {
                    char numGen=alpha.charAt(random2.nextInt(alpha.length()));
                    
                    Object yes = numGen;
                    
                    String number = yes.toString();
                    txtinvoiceid.setText("INV"+val+number);
                }
        
        

        }
        
        
    void ShowDate (){
        Date date = new Date();
            SimpleDateFormat s = new SimpleDateFormat("dd-MMM-YYYY");
            txtDate.setText(s.format(date));
        }
        
        void ShowTime (){
        
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Date date = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
            txtTime.setText(s.format(date));
                }
            } ).start();
        }
    
    
    public InvoiceSys() {
        initComponents();
        
        ShowDate();
        ShowTime();
        invoiceid();
        

        //Title of the window Assign
        this.setTitle("MiXed Invoice - Invoice Generate");
    }
    

    
     public InvoiceSys(String userName) {
      
            initComponents();
         txtUserlog.setText(userName);
         
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNewname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNewemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNewcontact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNewaddress = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtProdetails = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtProprice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnAddproduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtReceived = new javax.swing.JTextField();
        txtBal = new javax.swing.JTextField();
        btnProceed = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtProQuantity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtVAT = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCsid = new javax.swing.JTextField();
        txtProstat = new javax.swing.JTextField();
        btnMinus = new javax.swing.JButton();
        txtLog = new javax.swing.JLabel();
        txtUserlog = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtinvoiceid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 750));
        setMinimumSize(new java.awt.Dimension(1250, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/billing.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel2.setText("Invoice System");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Product Details");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/date-cal.png"))); // NOI18N

        txtDate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/time-watch.png"))); // NOI18N

        txtTime.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Name");

        txtNewname.setEditable(false);
        txtNewname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNewname.setText("Client Name!");
        txtNewname.setToolTipText("Client Name Will Appear Here!");
        txtNewname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewnameFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        txtNewemail.setEditable(false);
        txtNewemail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNewemail.setText("Client Email!");
        txtNewemail.setToolTipText("Email Will Appear Here!");
        txtNewemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewemailFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Contact");

        txtNewcontact.setEditable(false);
        txtNewcontact.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNewcontact.setText("Client Contact!");
        txtNewcontact.setToolTipText("Contact Will Appear Here!");
        txtNewcontact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewcontactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewcontactFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("Address");

        txtNewaddress.setEditable(false);
        txtNewaddress.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNewaddress.setText("Client Address!");
        txtNewaddress.setToolTipText("Client Address Will Appear Here!");
        txtNewaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewaddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewaddressFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Client Details");

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setText("Product ID");

        txtProid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtProid.setText("Enter Product ID");
        txtProid.setToolTipText("Enter Product ID!");
        txtProid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProidFocusLost(evt);
            }
        });
        txtProid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProidActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("Product Name");

        txtProname.setEditable(false);
        txtProname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtProname.setText("Product Name");
        txtProname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPronameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPronameFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("Product Description");

        txtProdetails.setEditable(false);
        txtProdetails.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtProdetails.setText("Product Details");
        txtProdetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProdetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdetailsFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel14.setText("Stock Status");

        txtProprice.setEditable(false);
        txtProprice.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtProprice.setText("Product Price (Per Unit)");
        txtProprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPropriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPropriceFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel15.setText("Unit Price");

        btnAddproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/plus_add-32x32.png"))); // NOI18N
        btnAddproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddproductMouseClicked(evt);
            }
        });

        invoiceTable.setAutoCreateRowSorter(true);
        invoiceTable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Details", "Unit Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invoiceTable);

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel16.setText("Payment Details");

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel17.setText("Amount Received");

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel18.setText("Sub-Total");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtReceived.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtBal.setEditable(false);
        txtBal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtBal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBalMouseClicked(evt);
            }
        });

        btnProceed.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnProceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/proceed - 32 X 32.png"))); // NOI18N
        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/reset - 32 X 32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/close - 32 X 32.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/print - 32 X 32.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel19.setText("Balance / Due");

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel20.setText("Quantity");

        txtProQuantity.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel21.setText("Inc. VAT (15%)");

        txtVAT.setEditable(false);
        txtVAT.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtVAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVATMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel22.setText("CSID");

        txtCsid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtCsid.setText("Enter CSID!");
        txtCsid.setToolTipText("Type CSID! To Find Customer!");
        txtCsid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCsidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCsidFocusLost(evt);
            }
        });
        txtCsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCsidActionPerformed(evt);
            }
        });

        txtProstat.setEditable(false);
        txtProstat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtProstat.setText("Stock Status");

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/minus- 32 X 32.png"))); // NOI18N
        btnMinus.setToolTipText("Delete Entry From Above!");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        txtLog.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtLog.setText("Logged in As -");

        txtUserlog.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel23.setText("Invoice No:");

        txtinvoiceid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtinvoiceid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtinvoiceidMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCsid, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNewname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNewemail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNewcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNewaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProid, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtProprice))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdetails, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtProname))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProstat, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnAddproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLog, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtUserlog, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtinvoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinus)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBal, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtReceived, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVAT)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProceed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNewname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtCsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtProid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtProname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtProstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtProprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnMinus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtinvoiceid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserlog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLog, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProceed)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnReset)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrint))))
                .addGap(142, 142, 142))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewnameFocusGained
        // TODO add your handling code here:
        if (txtNewname.getText().equals("Client Name!")){
            txtNewname.setText("");
            txtNewname.setForeground(new Color(0,0,0));

        }

    }//GEN-LAST:event_txtNewnameFocusGained

    private void txtNewnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewnameFocusLost
        // TODO add your handling code here:
        if (txtNewname.getText().equals("")){
            txtNewname.setText("Client Name!");
            txtNewname.setForeground(new Color(153,153,153));

        }

    }//GEN-LAST:event_txtNewnameFocusLost

    private void txtNewemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewemailFocusGained
        // TODO add your handling code here:
        if (txtNewemail.getText().equals("Client Email!")){
            txtNewemail.setText("");
            txtNewemail.setForeground(new Color(0,0,0));

        }
    }//GEN-LAST:event_txtNewemailFocusGained

    private void txtNewemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewemailFocusLost
        // TODO add your handling code here:

        if (txtNewemail.getText().equals("")){
            txtNewemail.setText("Client Email!");
            txtNewemail.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_txtNewemailFocusLost

    private void txtNewcontactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewcontactFocusGained
        // TODO add your handling code here:
        if (txtNewcontact.getText().equals("Client Contact!")){
            txtNewcontact.setText("");
            txtNewcontact.setForeground(new Color(0,0,0));

        }
    }//GEN-LAST:event_txtNewcontactFocusGained

    private void txtNewcontactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewcontactFocusLost
        // TODO add your handling code here:
        if (txtNewcontact.getText().equals("")){
            txtNewcontact.setText("Client Contact!");
            txtNewcontact.setForeground(new Color(153,153,153));

        }

    }//GEN-LAST:event_txtNewcontactFocusLost

    private void txtNewaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewaddressFocusGained
        // TODO add your handling code here:
        if (txtNewaddress.getText().equals("Client Address!")){
            txtNewaddress.setText("");
            txtNewaddress.setForeground(new Color(0,0,0));

        }

    }//GEN-LAST:event_txtNewaddressFocusGained

    private void txtNewaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewaddressFocusLost
        // TODO add your handling code here:
        if (txtNewaddress.getText().equals("")){
            txtNewaddress.setText("Client Address!");
            txtNewaddress.setForeground(new Color(153,153,153));

        }

    }//GEN-LAST:event_txtNewaddressFocusLost

    private void txtProidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProidFocusGained
        // TODO add your handling code here:
        if (txtProid.getText().equals("Enter Product ID")){
            txtProid.setText("");
            txtProid.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtProidFocusGained

    private void txtProidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProidFocusLost
        // TODO add your handling code here:

        if (txtProid.getText().equals("")){
            txtProid.setText("Enter Product ID");
            txtProid.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtProidFocusLost

    private void txtPronameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPronameFocusGained
        // TODO add your handling code here:
        if (txtProname.getText().equals("Type Product Name")){
            txtProname.setText("");
            txtProname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPronameFocusGained

    private void txtPronameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPronameFocusLost
        // TODO add your handling code here:
        if (txtProname.getText().equals("")){
            txtProname.setText("Type Product Name");
            txtProname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPronameFocusLost

    private void txtProdetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdetailsFocusGained
        // TODO add your handling code here:
        if (txtProdetails.getText().equals("Describe Product Details")){
            txtProdetails.setText("");
            txtProdetails.setForeground(new Color(0,0,0));
        }

    }//GEN-LAST:event_txtProdetailsFocusGained

    private void txtProdetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdetailsFocusLost
        // TODO add your handling code here:
        if (txtProdetails.getText().equals("")){
            txtProdetails.setText("Describe Product Details");
            txtProdetails.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtProdetailsFocusLost

    private void txtPropriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPropriceFocusGained
        // TODO add your handling code here:
        if (txtProprice.getText().equals("Add Product Price (Per Unit)")){
            txtProprice.setText("");
            txtProprice.setForeground(new Color(0,0,0));
        }

    }//GEN-LAST:event_txtPropriceFocusGained

    private void txtPropriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPropriceFocusLost
        // TODO add your handling code here:
        if (txtProprice.getText().equals("")){
            txtProprice.setText("Add Product Price (Per Unit)");
            txtProprice.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPropriceFocusLost

    private void txtProidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProidActionPerformed
        // TODO add your handling code here:
        String productid= txtProid.getText().trim();
        String sql = "select * from newproduct where productid like '"+productid+"%'";
        
            try {
                pst=dbConn.getCon().prepareStatement(sql);
                ResultSet rs;
                rs = pst.executeQuery(); 
                
                if(rs.next()){
                    
                 txtProid.setText(rs.getString(1));
                 txtProname.setText(rs.getString(2));
                 txtProdetails.setText(rs.getString(3));
                 txtProstat.setText(rs.getString(5));
                 txtProprice.setText(rs.getString(4));
                 txtProQuantity.setText("1");
                
                }else{
                
                 txtProname.setText("");
                 txtProdetails.setText("");
                 txtProstat.setText("");
                 txtProprice.setText("");
                 txtProQuantity.setText("");
                }
                
            } catch (ClassNotFoundException ex) {
                
                JOptionPane.showMessageDialog(this, "Failed!");
                Logger.getLogger(InvoiceSys.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(InvoiceSys.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_txtProidActionPerformed

    private void btnAddproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddproductMouseClicked
        // TODO add your handling code here:
        try {
            float price = Float.parseFloat(txtProprice.getText());
        int qty = Integer.parseInt(txtProQuantity.getText());
        float total = price*qty;
        
        DefaultTableModel tblForList = (DefaultTableModel)invoiceTable.getModel();
        tblForList.addRow(new Object[] {txtProid.getText(),txtProname.getText(),  txtProdetails.getText(),price,qty,total});
        

        
        subtotal= subtotal+total;
        String totalDisplay = String.valueOf(subtotal);
        txtSubtotal.setText(totalDisplay);
        
      

        
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnAddproductMouseClicked

    private void txtVATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVATMouseClicked
        // TODO add your handling code here:
        try {
            String totalAmount = txtSubtotal.getText();

            float vatCalculate = Float.parseFloat(totalAmount);

            subtotal=vatCalculate +(vatCalculate*15/100);
            String totalDisplay = String.valueOf(subtotal);
             txtVAT.setText(totalDisplay);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Place the item first!");
        }
          
        
        

    }//GEN-LAST:event_txtVATMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        
        int lout = JOptionPane.showConfirmDialog(null, "Want To Leave Invoice System!", "Select ",JOptionPane.YES_NO_OPTION);
        
        if (lout ==0){
            setVisible(false);
            new Homepage().setVisible(true);
            
        
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new InvoiceSys().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCsidActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            String sql = "select csid, name, email, contact, address from newuser where csid=?";
            ResultSet rs;
            pst=dbConn.getCon().prepareStatement(sql);
            pst.setString(1, txtCsid.getText().trim());
            
            rs = pst.executeQuery();
            
            while(rs.next()){
            txtCsid.setText(rs.getString(1));
            txtNewname.setText(rs.getString(2));
            txtNewemail.setText(rs.getString(3));
            txtNewcontact.setText(rs.getString(4));
            txtNewaddress.setText(rs.getString(5));
            
            }
              
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Client ID Not Exist!");
            Logger.getLogger(UpdateClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCsidActionPerformed

    private void txtCsidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCsidFocusGained
        // TODO add your handling code here:
         if (txtCsid.getText().equals("Enter CSID!")){
            txtCsid.setText("");
            txtCsid.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtCsidFocusGained

    private void txtCsidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCsidFocusLost
        // TODO add your handling code here:
        if (txtCsid.getText().equals("")){
            txtCsid.setText("Enter CSID!");
            txtCsid.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_txtCsidFocusLost

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:

    DefaultTableModel tableInvoice = (DefaultTableModel)invoiceTable.getModel();
        
        if (invoiceTable.getSelectedRowCount()==1){
        tableInvoice.removeRow(invoiceTable.getSelectedRow());
           float sum = 0;

           for (float i = 0; i < invoiceTable.getRowCount(); i++) {
               
           sum = sum + Float.parseFloat(tableInvoice.getValueAt((int)i, 5).toString());
            
       
           txtSubtotal.setText(Float.toString(sum));
        
        }
           if(invoiceTable.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(this, "Item Removed From List!");
        }
                else{
        JOptionPane.showMessageDialog(this, "Sorry");
        
        }
        
        }
        
        
             
//           DefaultTableModel tableInvoice = (DefaultTableModel)invoiceTable.getModel();
//           tableInvoice.removeRow(invoiceTable.getSelectedRow());
//           float sum = 0;
//
//           for (float i = 0; i < invoiceTable.getRowCount(); i++) {
//               
//           sum = sum + Float.parseFloat(tableInvoice.getValueAt((int)i, 5).toString());
//            
//       
//           txtSubtotal.setText(Float.toString(sum));
//        }
    }//GEN-LAST:event_btnMinusActionPerformed
    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        String InvoiceID = "";
        String csid= txtCsid.getText();
        String name = txtNewname.getText();
        String contact = txtNewcontact.getText();
        String address=txtNewaddress.getText();
        


        String path="C:\\Users\\Al-RaZi\\Documents\\NetBeansProjects\\InvoiceSystem\\Print";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+name + " "+ txtDate.getText()+".pdf" ) );
            doc.open();
            Paragraph paragraph01= new Paragraph("                  MiXed Invoice System\n                  Contact Number: +880171000000\n"
                    + "\n"
                    + "\n");
            doc.add(paragraph01);
            
            Paragraph paragraph02 = new Paragraph("Date & Time: "+txtDate.getText()+" "+txtTime.getText()+"\nClient Details: \nCSID: "+csid+"\nName: "+name+"\nContact: "+contact+"\nAddress: "+address+"\n"
                    + "\n"
                    + "\n"
                    + "\n ");
            doc.add(paragraph02);
            
            PdfPTable itemTable = new PdfPTable(5);
            
            itemTable.addCell("Product ID");
            itemTable.addCell("Product Name");
            itemTable.addCell("Product Details");
            itemTable.addCell("Price(Per Unit)");
            itemTable.addCell("Sub Total");

            for (int i = 0; i < invoiceTable.getRowCount(); i++) {
                String p = invoiceTable.getValueAt(i, 0).toString();
                String pn = invoiceTable.getValueAt(i,1 ).toString();
                String pd = invoiceTable.getValueAt(i, 2).toString();
                String pu = invoiceTable.getValueAt(i, 3).toString();
                String st = invoiceTable.getValueAt(i, 4).toString();
                
                itemTable.addCell(p);
                itemTable.addCell(pn);
                itemTable.addCell(pd);
                itemTable.addCell(pu);
                itemTable.addCell(st);
            }
            
            
            doc.add(itemTable);
            Paragraph paragraph03 = new Paragraph("\nTotal: "+txtSubtotal.getText()+"\nVAT(15%): "+txtVAT.getText()+"\nBalance: "+txtBal.getText()+"\n\n"
                    + "\n Thank You For Using MiXed Invoice Syatem\n");
            doc.add(paragraph03);
            
            JOptionPane.showMessageDialog(this, "Invoice Printed Successful!");
            setVisible(false);
            new InvoiceSys().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        
        
        
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtBalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBalMouseClicked
        // TODO add your handling code here:
         try {
             
            String totalAmount = txtSubtotal.getText();

            float vatCalculate = Float.parseFloat(totalAmount);

            subtotal=vatCalculate +(vatCalculate*15/100);
            String totalDisplay = String.valueOf(subtotal);
            
            String recvAmount = txtReceived.getText();
            float amountReceived =  Float.parseFloat(recvAmount);
            
            float finalAmount= (amountReceived-subtotal);
            String totalBalance=String.valueOf(finalAmount);
           txtBal.setText(totalBalance);
            

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Place the item first!");
        }
        
    }//GEN-LAST:event_txtBalMouseClicked

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        
         DateTimeFormatter dateCreate= DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDateTime now = LocalDateTime.now();
        String date = dateCreate.format(now);
        
        DateTimeFormatter timeCreate= DateTimeFormatter.ofPattern("hh:mm:ss a");
        LocalDateTime tm = LocalDateTime.now();
        String time = timeCreate.format(tm);
        
        String sql = "insert into transactions(invoiceid, csid, name, contact, address, productname, productqty, vatamount, total, date_created, time_created, created_by) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
        
            try {
                pst=dbConn.getCon().prepareStatement(sql);
                
            pst.setString(1, txtinvoiceid.getText().toString().trim());
            pst.setString(2, txtCsid.getText().trim());
            pst.setString(3, txtNewname.getText().trim());
            pst.setString(4, txtNewcontact.getText().trim());
            pst.setString(5, txtNewaddress.getText().trim());
            pst.setString(6, txtProname.getText().trim());
            pst.setString(7, txtProQuantity.getText().trim());
            pst.setString(8, txtVAT.getText().trim());
            pst.setString(9, txtBal.getText().trim());
            pst.setString(10, time);
            pst.setString(11, date);
            pst.setString(12, txtUserlog.getText().trim());
                
             pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data Saved Successful!");
            pst.close();
            dbConn.getCon().close();
             
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InvoiceSys.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(InvoiceSys.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        
        
        
    }//GEN-LAST:event_btnProceedActionPerformed

    private void txtinvoiceidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtinvoiceidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoiceidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddproduct;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProceed;
    private javax.swing.JButton btnReset;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtCsid;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtLog;
    private javax.swing.JTextField txtNewaddress;
    private javax.swing.JTextField txtNewcontact;
    private javax.swing.JTextField txtNewemail;
    private javax.swing.JTextField txtNewname;
    private javax.swing.JTextField txtProQuantity;
    private javax.swing.JTextField txtProdetails;
    private javax.swing.JTextField txtProid;
    private javax.swing.JTextField txtProname;
    private javax.swing.JTextField txtProprice;
    private javax.swing.JTextField txtProstat;
    private javax.swing.JTextField txtReceived;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JLabel txtTime;
    private javax.swing.JLabel txtUserlog;
    private javax.swing.JTextField txtVAT;
    private javax.swing.JLabel txtinvoiceid;
    // End of variables declaration//GEN-END:variables
}
