/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicesystem.home;

import invoiceProject.dbConinvoice;
import invoicesystem.home.Homepage;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Al-RaZi
 */
public class Login extends javax.swing.JFrame {

            dbConinvoice dbConn = new dbConinvoice();
        PreparedStatement pst;
        
        private void clear(){
            
            txtUsername.setText("");
            txtPassword.setText("");
        }
        
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        

        //Title of the window Assign
        this.setTitle("MiXed Invoice - Login!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passShow = new javax.swing.JCheckBox();
        btnDiscard = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1020, 665));
        setMinimumSize(new java.awt.Dimension(1005, 655));
        setPreferredSize(new java.awt.Dimension(1005, 655));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passShow.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        passShow.setText("Show Password");
        passShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passShowActionPerformed(evt);
            }
        });
        getContentPane().add(passShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 328, 39));

        btnDiscard.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnDiscard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logout.png"))); // NOI18N
        btnDiscard.setText("Discard");
        btnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 170, -1));

        btnSignin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/login.png"))); // NOI18N
        btnSignin.setText("SignIn");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 163, -1));

        txtUsername.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 394, 44));

        txtPassword.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 394, 47));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setText("MiXed Invoice System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 140, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice System Login!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 150, 47));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 150, 44));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Sheild Sign.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 130, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Login - BG.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Login - BG -Header.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardActionPerformed
        // TODO add your handling code here:
        int discard = JOptionPane.showConfirmDialog(null, "Do You Want to Discard Session!","Select",JOptionPane.YES_NO_OPTION);
        
        if (discard==0){
        System.exit(0);
        
        }
    }//GEN-LAST:event_btnDiscardActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
         String sql =  "select username, password from appusers where username=? and password=? ";
           ResultSet rs;
           
           String user = txtUsername.getText().trim();
           String pass = txtPassword.getText();
           
                try {
                    pst = dbConn.getCon().prepareStatement(sql);
                    pst.setString(1, user);
                    pst.setString(2, pass);
                     rs=pst.executeQuery();
                    
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this, "Welcome to MiXed Invoice System");
                        setVisible(false);
                         new Homepage(rs.getString(1)).setVisible(true);
                        
                       
                        
//                        new Homepage().setVisible(true);
                        pst.close();
                        dbConn.getCon().close();
                        clear();
                        dispose();
                        
                    }else{
                    
                    JOptionPane.showMessageDialog(this, "UserName / Password is Invalid! / Missing!");
                    }
                    
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "UserName or Password Missing!");
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }

    }//GEN-LAST:event_btnSigninActionPerformed

    private void passShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passShowActionPerformed
        // TODO add your handling code here:
        
        if(passShow.isSelected()){
        txtPassword.setEchoChar((char)0);
        }
        else{
        txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_passShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscard;
    private javax.swing.JButton btnSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox passShow;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
