/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package invoicesystem.home;

import invoiceProject.dbConinvoice;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author Al-RaZi
 */
public class UpdateProducts extends javax.swing.JFrame {

    dbConinvoice dbConn = new dbConinvoice();
    PreparedStatement pst;
    
    /**
     * Creates new form UpdateUser
     */
    public UpdateProducts() {
        initComponents();

        //Title of the window Assign
        this.setTitle("MiXed Invoice - Update Products");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtProsearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtProndetails = new javax.swing.JTextField();
        txtProname = new javax.swing.JTextField();
        txtProid = new javax.swing.JTextField();
        txtProprice = new javax.swing.JTextField();
        btnUpdateproduct = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtProstat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel1.setText("Update Products");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/update-product.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, -1));

        txtProsearch.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtProsearch.setText("Enter The Product ID");
        txtProsearch.setToolTipText("Search With Product ID!");
        txtProsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProsearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProsearchFocusLost(evt);
            }
        });
        getContentPane().add(txtProsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 430, -1));

        btnSearch.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/search - 32.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProndetails.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel2.add(txtProndetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 380, -1));

        txtProname.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel2.add(txtProname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 380, -1));

        txtProid.setEditable(false);
        txtProid.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel2.add(txtProid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 380, -1));

        txtProprice.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel2.add(txtProprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 380, -1));

        btnUpdateproduct.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnUpdateproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/update-product.png"))); // NOI18N
        btnUpdateproduct.setText("Update");
        btnUpdateproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateproductActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, 80));

        btnReset.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, 80));

        btnClose.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/close-exit.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 160, 80));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setText("Product ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 9, 160, 40));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Product ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Product Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Product Details");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 180, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("Unit Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 990, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 990, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Stock Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        txtProstat.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtProstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Availability", "In-Stock", "Stock-Out" }));
        jPanel2.add(txtProstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 380, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 990, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        try {
            // TODO add your handling code here:
            String sql = "select productid, product_name, product_details, product_price, stock_status from newproduct where productid=?";
            ResultSet rs;
            pst=dbConn.getCon().prepareStatement(sql);
            pst.setString(1, txtProsearch.getText().trim());
            
            rs = pst.executeQuery();
            
            while(rs.next()){
            
            txtProid.setText(rs.getString(1));
            txtProname.setText(rs.getString(2));
            txtProndetails.setText(rs.getString(3));
            txtProprice.setText(rs.getString(4));
            txtProstat.setSelectedItem(rs.getString(5));

            
  
            
            }
 
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Product ID Not Found!");
            Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Product ID Not Found!");
            Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateProducts().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateproductActionPerformed
                    // TODO add your handling code here:
        String sql = "update newproduct set product_name=?, product_details=?, product_price=?, stock_status=? where productid=?";

            
         try {   
            pst = dbConn.getCon().prepareStatement(sql);
            

            pst.setString(1, txtProname.getText().trim());
            pst.setString(2, txtProndetails.getText().trim());
            pst.setString(3, txtProprice.getText().trim());
            pst.setString(4, txtProstat.getSelectedItem().toString().trim());
            pst.setInt(5, Integer.parseInt(txtProid.getText().trim()));
            
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product Update Successful");
            
             pst.close();
            dbConn.getCon().close();
            
             setVisible(false);
             new UpdateProducts().setVisible(true);
            

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Operation Failed!");
            Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
        } 
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Operation Failed!");
            Logger.getLogger(UpdateProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        
    }//GEN-LAST:event_btnUpdateproductActionPerformed

    private void txtProsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProsearchFocusGained
        // TODO add your handling code here:
        
        if (txtProsearch.getText().equals("Enter The Product ID")){
        txtProsearch.setText("");
        txtProsearch.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtProsearchFocusGained

    private void txtProsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProsearchFocusLost
        // TODO add your handling code here:
        if (txtProsearch.getText().equals("")){
        txtProsearch.setText("Enter The Product ID");
        txtProsearch.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtProsearchFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateproduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtProid;
    private javax.swing.JTextField txtProname;
    private javax.swing.JTextField txtProndetails;
    private javax.swing.JTextField txtProprice;
    private javax.swing.JTextField txtProsearch;
    private javax.swing.JComboBox<String> txtProstat;
    // End of variables declaration//GEN-END:variables
}
